version: '2'

services:
  mongo:
    image: phgache/mymongo:latest
    volumes:
      - "/var/data"
    restart: always
  multichanneltodo.core.api:
    depends_on:
      - mongo
    image: phgache/multichanneltodoapi:Debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "8080:80"
    volumes:
      - .:/app
    environment:
      - REMOTE_DEBUGGING=${REMOTE_DEBUGGING}
      - NetCore_MongoConnection=mongodb://mongo:27017
      - NetCore_Database=multichanneltodo
