version: '2'

services:
  multichanneltodo.core.api:
    image: username/multichanneltodo.core.api:Debug
    environment:
      - REMOTE_DEBUGGING=${REMOTE_DEBUGGING}
    ports:
      - "80:80"
    volumes:
      - .:/app
