version: '2'

services:
  mongo:
    image: phgache/mymongo:latest
    volumes:
      - "/var/data"
    restart: always
  multichanneltodo.core.api:
    depends_on:
      - mongo
    image: phgache/multichanneltodoapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - NetCore_MongoConnection=mongodb://mongo:27017
      - NetCore_Database=multichanneltodo