version: '2'

services:
  multichanneltodo.core.api:
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
    volumes:
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    environment:
      - NetCore_MongoConnection=mongodb://mongo:27017
      - NetCore_Database=multichanneltodo