version: '2'

services:
  mongo:
    image: phgache/mymongo:latest
    volumes:
      - "/var/data"
    restart: always
  multichanneltodo.api:
    depends_on:
      - mongo
    image: phgache/multichanneltodoapi:latest
    links:
      - mongo
    ports:
    - "${HOST_PORT}:${MULTICHANNELTODO_API_PORT}"