version: '2'

services:
  multichanneltodo.front:
    image: phgache/multichanneltodofront:latest
    expose:
    - "5000"
    environment:
      - DNX_apipath=${MULTICHANNELTODO_API_PATH}
      - DNX_env=${MULTICHANNELTODO_ENV}
      - "constraint:container!=~front*"
      - "constraint:node!=consul0"
    networks:
      - front

  lbfront:
    image: phgache/haproxy:latest
    ports:
      - "${MULTICHANNELTODO_FRONT_PORT}:80"
    environment:
      - "APP_NAME=multichanneltodofront"
      - "CONSUL_URL=${MULTICHANNELTODO_CONSUL_URL}"
      - "constraint:node==consul0"
    networks:
      - front

networks:
  front:
    driver: overlay
