version: '2'

services:
  multichanneltodo.core.front:
    image: phgache/multichanneltodofront
    ports:
      - "80:80"
    environment:
      - NetCore_Env=${NETCORE_ENV}
      - NetCore_ApiPath=${NETCORE_APIPATH}
