version: '2'

services:
  multichanneltodofront:
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
    volumes:
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    environment:
      - NetCore_Env=Development
      - NetCore_ApiPath=http://localhost:32778/api