version: '2'

services:
  multichanneltodo.core.front:
    image: phgache/multichanneltodofront:Debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    environment:
      - REMOTE_DEBUGGING=${REMOTE_DEBUGGING}
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      - NetCore_Env=${NETCORE_ENV}
      - NetCore_ApiPath=${NETCORE_APIPATH}